version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: electric_heater_controller
      POSTGRES_PASSWORD: electric_heater_controller_password
      POSTGRES_DB: electric_heater_controller

  electric-heater-controller:
    image: docker-registry.nolife.cyou/electric-heater-controller
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=electric_heater_controller
      - DB_PASSWORD=electric_heater_controller_password
      - DB_NAME=electric_heater_controller
      - DB_PORT=5432